
# constante para el calculo de las rondas 

VELOCIDAD_MAXIMA_ROBOT = 20
VELOCIDAD_MISIL = 100
TAMAÑO_ROBOT = 25

TIEMPO_ESPERA_MISIL = 5

DAÑO_POR_CHOQUE = 2
DAÑO_POR_EXPLOCION_5M = 10
DAÑO_POR_EXPLOCION_20M = 5
DAÑO_POR_EXPLOCION_40M = 3

MAX_INT = 10001
MAX_DISTANCIA = 100000

RONDAS_SIN_DISPARAR = 3

TIEMPOENTREMISIL = 0.1